#!/bin/bash

TPL="/path/to/git/nuclei-templates"
DIR="${BASH_SOURCE%/*}"

. "${DIR}/functions.sh"

parseArgs "$@"

cd "${TPL}"
isUpdated
CUR=$(getHead)
git pull origin master &>/dev/null
NOW=$(getHead)
CHG=$(getChanges "${CUR}..${NOW}")

if [[ -n ${CHG} ]]
then
        nuclei ${1} ${2} $(echo "${CHG}" | sed "s/^/-t /" | tr "\n" " ") -o "${DIR}/$(basename "${2}" .txt)_nuclei-continuous-results.txt"
fi
